- hosts: symfony  # exeutes on the build container
  gather_facts: no
  tasks:
  - name: Remove any existing dist archive
    file:
      path: /dist/symfony.gz
      state: absent

  - name: Stat the symfony/bin directory
    stat:
      path: /symfony/symfony/bin
    register: sym 

  - name: Archive the source files when symfony/bin found
    command: tar -cvzf /symfony/dist/symfony.gz .
    args:
      chdir: /symfony/symfony
    when: sym.stat.exists

- hosts: mariadb
  roles:
  - role: chouseknecht.mariadb-container
    mariadb_datadir: /var/lib/mysql
    mariadb_socket: /var/lib/mysql/mysql.sock
    mariadb_port: 3306

- hosts: nginx
  vars:
    nginx_default_port: 8888
    nginx_default_server_name: "" 
    nginx_package_name: nginx
    nginx_error_log: /var/log/nginx/error.log warn
    nginx_access_log: /var/log/nginx/access.log
    nginx_conf_file_path: /etc/nginx/nginx.conf
    nginx_mime_file_path: /etc/nginx/mime.types
    nginx_pidfile: /var/run/nginx.pid
  roles:
  - role: chouseknecht.nginx-container
  - role: configure-php-fpm
  - role: supervisord

- hosts: symfony
  roles:
  - role: chouseknecht.symfony-container
  - role: configure-symfony

